name: persimmon-api-cloud-run
 
on:
  push:
    branches:
      - stage
  workflow_dispatch:
    inputs:
      secret_input:
        description: 'Provide the secret value'
        required: true
env:
  REPO_NAME: persimmon-api-stage
 
jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Compare secret value
        run: |
          if [[ "${GITHUB_REF}" != "refs/heads/main" && "${{ github.event.inputs.secret_input }}" != "${{ secrets.USER_INPUT }}" ]]; then
            echo "Secret values do not match. Exiting..."
            exit 1
          fi
          echo "Secret values match, proceeding with the job..."
      - name: Compare secret matched
        run: echo "Secret values match, proceeding with the job..."
