name: persimmon-api-cloud-run
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Specify the branch to deploy from'
        required: true
      secret_input:
        description: 'Provide the secret value'
        required: true 
env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  REPO_NAME: persimmon-api-stage
 
jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"
 
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
 
      - name: Enable component beta
        run: gcloud components install beta
 
      - name: Use gcloud CLI
        run: gcloud info
 
      - name: What is gcloud version?
        run: gcloud --version
 
      - name: Authorize Docker push
        run: gcloud auth configure-docker
