name: Deploy to AWS Windows Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Use windows-latest for the latest Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-region: eu-north-1

      # Add more steps to deploy your code to AWS on Windows
